name: First workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        
        steps: 
        - name: Welcome
          run: echo "Hello!"
        - name: List files
          run: ls -la
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: List files
          run: ls -la
    